apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/rust/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - script: |
            #!/bin/sh
            export SUBDIR="source"
            echo "git cloning url: $REPO_URL version $PULL_BASE_REF@$PULL_BASE_SHA to dir: $SUBDIR"
            git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
            git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
            git config --global credential.helper store
            git clone $REPO_URL $SUBDIR
            cd $SUBDIR
            git reset --hard $PULL_BASE_SHA
            echo "checked out revision: $PULL_BASE_REF@$PULL_BASE_SHA to dir: $SUBDIR"
          image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.19.0
          name: git-clone
          resources: { }
          workingDir: /workspace
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: unit-test
          volumeMounts:
          - name: coveralls-repo-tokens
            mountPath: /coveralls
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            mkdir /kaniko/cache
            # Write a random value to a file named "bust" here to force the test Dockerfile
            # to re-run tests and code coverage without breaking the dependency and build cache
            head -c 32 /dev/random > bust
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile.test --no-push --cache=true --cache-dir=/kaniko/cache --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME/cache --build-arg REPO_TOKEN=$(cat /coveralls/$APP_NAME)
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: unit-test-2
          volumeMounts:
          - name: crates-io-token
            mountPath: /usr/local/cargo
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            sleep 999999
        - name: promote-changelog
          resources: {}
        volumes:
        - name: coveralls-repo-tokens
          secret:
            secretName: coveralls-repo-tokens
  podTemplate: {}
  serviceAccountName: authorized-tekton-bot
  timeout: 240h0m0s
status: {}
